In [0]:
import numpy as np

In [0]:
arr = np.arange(0, 11)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr[4]

4

In [51]:
arr[1:5]

array([1, 2, 3, 4])

In [52]:
arr[:5]

array([0, 1, 2, 3, 4])

In [53]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [54]:
arr + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [55]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
slice_of_arr = arr[0:6]

In [0]:
slice_of_arr[:] = 99

In [60]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [61]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [0]:
arr_copy = arr.copy()

In [0]:
arr_copy[:] = 100

In [65]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [66]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [0]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [68]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [69]:
arr_2d[1][1]

25

In [70]:
arr_2d[1, 1]

25

In [71]:
arr_2d[2, 2]

45

In [72]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [0]:
arr = np.arange(1, 11)

In [74]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [0]:
bool_arr = arr > 4

In [80]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [81]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [82]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [83]:
arr[arr <= 6]

array([1, 2, 3, 4, 5, 6])