In [0]:
import numpy as np

In [0]:
list1 = [1, 2, 3]

In [0]:
arr = np.array(list1)

In [0]:
list1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [0]:
matrix = np.array(list1)

In [9]:
matrix.shape

(3, 3)

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.ones((5, 5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [18]:
np.ones(5) * 100

array([100., 100., 100., 100., 100.])

In [20]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.random.rand(5)

array([0.03588372, 0.05018399, 0.32584765, 0.97628058, 0.08183127])

In [26]:
np.random.rand(3, 3)

array([[0.32627319, 0.81233622, 0.03976476],
       [0.46117116, 0.91981329, 0.27503118],
       [0.84750922, 0.46002576, 0.85193063]])

In [28]:
np.random.randn(10)

array([ 0.51563964, -1.41095961,  0.02358552, -0.11532402, -1.05721288,
        0.28855885, -0.73914813,  0.50809724,  0.1191881 , -1.26562264])

In [32]:
np.random.randint(1, 100, 20)

array([ 7, 91, 54, 66, 97, 88, 53,  2, 59, 92,  4, 96, 16, 89, 46, 87, 33,
       27, 79, 90])

In [34]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [0]:
arr = np.arange(25)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [0]:
ranarr = np.random.randint(0, 50, 10)

In [38]:
ranarr

array([47,  9, 13, 40,  4, 40, 28,  0, 46,  5])

In [39]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
ranarr.max()

47

In [41]:
ranarr.min()

0

In [42]:
ranarr.argmax()

0

In [45]:
ranarr.argmin()

7

In [46]:
ranarr.dtype

dtype('int64')